services:
  nginx:
    image: nginx
    container_name: certis.bwc.nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html

    networks:
      - certis.bwc

networks:
  certis.bwc:
