services:
  pypathfinder:
    build:
      context: pypathfinder
      dockerfile: ./Dockerfile
    image: pypathfinder.medical:2.0.0
    container_name: pypathfinder
    restart: unless-stopped
    ports:
      - "9012:9012"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - REDIS_SERVER=${REDIS_SERVER}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ZICARE_USERNAME=${ZICARE_USERNAME}
      - ZICARE_PASSWORD=${ZICARE_PASSWORD}
      - ZICARE_BASEURL=${ZICARE_BASEURL}
    volumes:
      - ./data:/opt/pathfinder/data
    networks:
      - pathfinder.medical

  gopathfinder:
      build:
        context: gopathfinder
        dockerfile: ./Dockerfile
      image: gopathfinder.medical:2.0.0
      container_name: gopathfinder
      restart: unless-stopped
      ports:
        - "9013:9013"
      environment:
        - MONGO_URI=${MONGO_URI}
        - MISTRAL_API_KEY=${MISTRAL_API_KEY}
        - REDIS_SERVER=${REDIS_SERVER}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - ZICARE_USERNAME=${ZICARE_USERNAME}
        - ZICARE_PASSWORD=${ZICARE_PASSWORD}
        - ZICARE_BASEURL=${ZICARE_BASEURL}
      volumes:
        - ./data:/opt/pathfinder/data
      networks:
        - pathfinder.medical

  kong:
    image: kong:3.3.0
    container_name: kong
    restart: unless-stopped
    ports:
      - "8000:8000" # Kong Proxy
      - "8001:8001" # Kong Admin API
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_PLUGINS: bundled,request-transformer,cors,key-auth,acl,basic-auth
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      #- ./kong.conf:/etc/kong/kong.conf
    networks:
      - pathfinder.medical

networks:
  pathfinder.medical:
